### PR TITLE
Update Stable to v3.4.9 on dev

### PR DESCRIPTION
**Pull request by ashleighgregory**
## Description
  - v3.4.9 was released on 05/21/2020
  - update stable on dev

## Issues:

 https://github.com/vulk/cncf_ci/issues/344

## How has this been tested:

 - [ ]  Covered by existing integration testing
 - [ ]  Added integration testing to cover
 - [ ]  Tested with trigger client against
   - [ ]  cidev.cncf.ci
   - [ ]  dev.cncf.ci
   - [ ]  staging.cncf.ci
   - [ ]  cncf.ci (production)
 - [ ]  Browser tested on staging.cncf.ci
 - [x]  Have not tested

## Types of changes:
 - [ ]  Bug fix (non-breaking change which fixes an issue)
 - [ ]  New feature (non-breaking change which adds functionality)
 - [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [x] Version update

## Checklist:
  - [ ]  My change requires a change to the documentation
  - [ ]  I have updated the documentation accordingly
  - [x]  No updates required

### CODE REVIEW

**Comment by ashleighgregory** [comment]
@agentpoyo the build for v3.4.9 failed - https://gitlab.dev.cncf.ci/etcd-io/etcd/-/jobs/198225

```
JWT enabled
/builds/etcd-io/etcd
$ if [ "$BASE_URL" == "https://gitlab.cncf.ci" ]; then # collapsed multi-line command
curl -f -X GET https://devapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=etcd&ref=54ba9589114fc3fa5cc36c313550b3c0c0938c91&arch=AMD64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 422 
ERROR: Job failed: exit code 1

**Comment by agentpoyo** [comment]
Looks like it the build still fails with same error after dev.cncf.ci dashboard was fixed.

```
JWT enabled
/builds/etcd-io/etcd
$ if [ "$BASE_URL" == "https://gitlab.cncf.ci" ]; then # collapsed multi-line command
curl -f -X GET https://devapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=etcd&ref=54ba9589114fc3fa5cc36c313550b3c0c0938c91&arch=AMD64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 422 
ERROR: Job failed: exit code 1
```

**Comment by ashleighgregory** [comment]
[06-08-2020] v3.4.9 build is still failing - https://gitlab.dev.cncf.ci/etcd-io/etcd/-/jobs/198735

```
}
JWT enabled
/builds/etcd-io/etcd
$ if [ "$BASE_URL" == "https://gitlab.cncf.ci" ]; then # collapsed multi-line command
curl -f -X GET https://devapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=etcd&ref=54ba9589114fc3fa5cc36c313550b3c0c0938c91&arch=AMD64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
curl: (22) The requested URL returned error: 422 
ERROR: Job failed: exit code 1

**Comment by agentpoyo** [comment]
The URL used in the curl points to -> https://travis-ci.com/github/etcd-io/etcd/builds/167669554 which indicates this build is failing there as well.

Seems their last successful build was v3.3.22

**Comment by agentpoyo** [comment]
@taylor @denverwilliams @wavell 

If the curl output pulls back a "failed" status, is that what will cause our builds to halt and fail to continue the build? Or is there something else underlying here I might be missing?

When viewing https://devapi.cncf.ci/ciproxy/v1/ci_status_build/commit_ref?project=etcd&ref=54ba9589114fc3fa5cc36c313550b3c0c0938c91&arch=AMD64 it displays `status: failed`:
```
{"build_status":{"status":"failed","build_url":"https://travis-ci.com/etcd-io/etcd/builds/167669554 "}}
```

And https://travis-ci.com/etcd-io/etcd/builds/167669554 shows as a failed build.

**Pull request merged**
